project:
  type: website
  output-dir: docs

website:
  title: "CSC 496/696"
  navbar:
    logo: images/AU_mark.png
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

