project:
  type: website
  output-dir: docs

website:
  title: "CSC-496/696"
  navbar:
    logo: images/AU_mark.png
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: officehours.qmd
        text: Office Hours

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

