project:
  type: website
  output-dir: docs

website:
  title: "CSC-496/696"
  favicon: images/AU_mark.png
  navbar:
    logo: images/AU_mark.png
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule and Lecture Notes
      - href: officehours.qmd
        text: Office Hours
      - href: assignments.qmd
        text: Assignments

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

