---
title: "Assignments"
---

## Assignment 2 [Due Date: Tuesday, October 1 at 11:59pm ET]
* [Problem 1](https://colab.research.google.com/drive/1pN_uG29ZPf-WE6e0O6o7K9_O1n-5jW4X?usp=sharing){target="_blank"}
* [Problem 2](materials/A2_Problem2.pdf){target="_blank"}
* [Problem 3](https://colab.research.google.com/drive/110Z-9Ylt4eWL5J0HZVk_dJfoRirHu_Ay?usp=sharing){target="_blank"}

You will submit Problems 1 and 3 using the same approach as the last assignment. For Problem 2, follow the instructions in the PDF.

## Assignment 1 [Due Date: Tuesday, September 17 at 11:59pm ET]
* [Problem 1](https://colab.research.google.com/drive/1dAadrLAjwGnm_QOTJGYfnhzmUW41Qrh3?usp=sharing){target="_blank"}
* [Problem 2](https://colab.research.google.com/drive/1jmCaAjsk6wCjXLx8XlnayJVNaXRRAvvn?usp=sharing){target="_blank"}
* [Problem 3](https://colab.research.google.com/drive/1h2C8kNWOKqYYf3wWj0-ZBT5y6oGxFTCr?usp=sharing){target="_blank"}

For each problem, click "File" and "Save a copy to Drive." Save this file to your Google Drive, and then complete the assignment using your copy of the assignment. The file name will have "Copy" in it. Delete that, and put your initials at the end of the file separated by an underscore. For example, if I was turning in Assignment 1, I would rename the file to "A1_Problem1_PW.ipynb". 

After you complete the assignment, click "File," "Download," and select "Download .ipynb." Do this for all three problems. Submit each as a separate file on Canvas.

Be sure to put your name in the first cell of each notebook and the people you worked with (which may be different for each problem).

## Course Survey

Take the course survey [here](https://american.co1.qualtrics.com/jfe/form/SV_9TVxBqHAH5hjKxo){target="_blank"}. It is due on **Friday, August 30** (or the class after you enroll, if you are enrolling late).