---
title: "Natural Language Processing and Text as Data"
---

## Announcements
* The location of our class is now **DMTI 114**.

## Syllabus

[Click here for the syllabus](materials/CSC-496-696_NLP_TaD_Syllabus.pdf){target="_blank"}. The syllabus was last updated **Wednesday, August 21**.

## Course Information

-   **Class Time**: Tuesday/Friday, 4:05 PM - 5:20 PM

-   **Location**: DMTI 114

-   **Description**: In recent years, the quantity and quality of text data have dramatically increased, driving a surge in demand for tools to effectively analyze this data and unlocking new approaches to language modeling. This course introduces natural language processing (NLP) and text as data, focusing on practical applications and problem-solving. Using Python, the class covers fundamental NLP techniques, including text preprocessing, text classification, topic modeling, text embeddings, benchmarking and evaluation, transfer learning, and large language models (including generative LLMs). Applications involve working with data such as product reviews, tweets and other social media posts, news articles, and open-ended surveys to answer questions in domains like the social sciences and business.

-   **Textbook**: You will not need to purchase any textbooks. The books can be accessed online, through the University Library, or through Canvas. Readings may also come from other online sources. One of the tricky aspects of this class is that the field continues to evolve as the class goes on. Textbooks written even a few years ago may be out of date! Please have the readings completed before class. It is okay if you do not understand everything in the assigned reading.

    -   \[SLP\] *Speech and Language Processing*. Dan Jurafsky and James H. Martin. 3rd edition draft. 2024. Book can be accessed at <https://stanford.edu/~jurafsky/slp3/>{target="_blank"}.
    -   \[NLPT\] *Natural Language Processing with Transformers*. Lewis Tunstall, Leandro von Werra, and Thomas Wolf. 2022. Book can be accessed through the University Library.
    -   \[TaD\] *Text as Data: A New Framework for Machine Learning and the Social Sciences*. Justin Grimmer, Margaret E. Roberts, and Brandon M. Stewart. 2022. Readings will be provided on Canvas.
    -   \[ISLP\] *An Introduction to Statistical Learning with Applications in Python*. Gareth James, Daniela Witten, Trevor Hastie, and Robert Tibshirani. 2023. Book can be accessed at <https://www.statlearning.com/>{target="_blank"}.
    -   \[DL\] *Deep Learning*. Ian Goodfellow, Yoshua Bengio, and Aaron Courville. 2016. Book can be accessed at <https://www.deeplearningbook.org/>{target="_blank"}.

-   For all details about the class, check out the syllabus. I will let you know immediately if there are any updates to the schedule, policies, assignments, etc.

## Instructor Information

-   **Instructor**: Patrick Wu

-   **Email**: pwu \[at\] american.edu

-   **Instructor's Office**:

-   **Instructor's Office Hours**: Thursday, 3:00 PM - 5:00 PM or by [appointment](https://calendly.com/pwu-american/office-hours){target="_blank"}