---
title: "Schedule and Lecture Notes"
---

The schedule is subject to change – check back often!

## Important Dates

-   Class Survey: Due Friday, August 30
-   Assignment 1: Due Tuesday, September 17
-   Assignment 2: Due Tuesday, October 1
-   Midterm: In-class on Tuesday, October 8
-   Assignment 3: Due Tuesday, October 29
-   Project Proposal: Due Friday, November 8
-   Assignment 4: Due Tuesday, November 12
-   Assignment 5: Due Friday, November 22
-   Project Presentations: In-class on Tuesday, December 3 and Friday, December 6
-   Final Project: Due Friday, December 13 **at 5:00pm**

## Schedule

### Tuesday, August 27

-   Topics: Introduction, syllabus discussion
-   Readings: None
-   Class Events: Class survey goes out (due date: Friday, August 30)
-   Deadlines: None
-   Class slides: [Lecture 1](lectures/lecture1_20240827/lecture1_week1_F24.html){target="_blank"}
-   Lab: [Lecture 1 Lab](https://colab.research.google.com/drive/1vEolW8zK7o5pFyBKEdXh_VtN5NxMHvYy?usp=sharing){target="_blank"}

### Friday, August 30

-   Topics: Python review, Part I
-   Readings:
    -   [Overview of Colaboratory Features](https://colab.research.google.com/notebooks/basic_features_overview.ipynb){target="_blank"}
    -   ["An Informal Introduction to Python"](https://docs.python.org/3/tutorial/introduction.html){target="_blank"}
    -   ["More Control Flow Tools"](https://docs.python.org/3/tutorial/controlflow.html){target="_blank"}
-   Class Events: Assignment 1 goes out (due date: Tuesday, September 17)
-   Deadlines: Class survey
-   Class Slides: [Lecture 2](lectures/lecture2_20240830/lecture2_week1_F24.pdf){target="_blank"}
-   Lab: [Lecture 2 Lab](https://colab.research.google.com/drive/12x0LVRfYS9tGZPtedoU8-EcZmPIZqGhl?usp=sharing){target="_blank"}

### Tuesday, September 3

-   Topics: Python review, Part II
-   Readings:
    -   ["Data Structures"](https://docs.python.org/3/tutorial/datastructures.html){target="_blank"}
    -   ["Brief Tour of the Standard Library"](https://docs.python.org/3/tutorial/stdlib.html){target="_blank"}
    -   ["NumPy Fundamentals"](https://numpy.org/doc/stable/user/basics.html){target="_blank"}
-   Class Events: None
-   Deadlines: None
-   Class Slides: [Lecture 3](lectures/lecture3_20240903/lecture3_week2_F24.pdf){target="_blank"}
-   Lab: [Lecture 3 Lab](https://colab.research.google.com/drive/13zOmZ4Ls8o2i4-GcUw1z0u98MIQBZZSd?usp=sharing){target="_blank"}

### Friday, September 6

-   Topics: Linear algebra review
-   Readings:
    -   ["10 Minutes to pandas"](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html){target="_blank"}
    -   ["Introduction to Data Structures"](https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html){target="_blank"}
    -   ["Essence of Linear Algebra" - YouTube video series about linear algebra by 3Blue1Brown](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab){target="_blank"}
-   Class Events: This class will be prerecorded; **we will not be meeting in person**
-   Deadlines: None
-   Class Slides: [Lecture 4](lectures/lecture4_20240906/lecture4_week2_F24.html){target="_blank"}

### Tuesday, September 10

-   Topics: Text preprocessing: regular expressions, bag of words, n-grams, evaluation metrics
-   Readings:
    -   TaD Ch. 2 (on Canvas)
    -   TaD Ch. 5 (on Canvas)
    -   [SLP Ch. 2](https://stanford.edu/~jurafsky/slp3/2.pdf){target="_blank"}
-   Class events: None
-   Deadlines: None
-   Class Slides: [Lecture 5](lectures/lecture5_20240910/lecture5_week3_F24.html){target="_blank"}

### Friday, September 13
-   Topic: Text classification
-   Readings:
    -   ISLP Ch. 1
-   Class events: None
-   Deadlines: None
-   Class Slides: [Lecture 6](lectures/lecture6_20240913/lecture6_week3_F24.html){target="_blank"}
-   Lab: [Lecture 6 Lab](https://colab.research.google.com/drive/1ot8BPuqWrdYjVayVKxrF_LyjY5-x-9Zt?usp=sharing){target="_blank"}

### Tuesday, September 17
-   Topic: N-Gram Language Models - Naive Bayes
-   Readings:
    -   [SLP Ch. 3](https://stanford.edu/~jurafsky/slp3/3.pdf){target="_blank"}
    -   [SLP Ch. 4](https://stanford.edu/~jurafsky/slp3/4.pdf){target="_blank"}
-   Class events: Assignment 2 goes out (due date: Tuesday, October 1)
-   Deadlines: Assignment 1 due  
-   Class Slides: [Lecture 7](lectures/lecture7_20240917/lecture7_week4_F24.html){target="_blank"}
-   Lab: [Lecture 7 Lab](https://colab.research.google.com/drive/1Gt5_xhsFuwEfUF9xciEhLC-nkebVk5B5?usp=sharing){target="_blank"}

### Friday, September 20
-   Topic: N-Gram Language Models - Logistic Regression
-   Readings:
    -   ISLP Ch. 4
-   Class events: None
-   Deadlines: None
-   Class Slides: [Lecture 8](lectures/lecture8_20240920/lecture8_week4_F24.html){target="_blank"}
-   Lab: [Lecure 8 Lab](https://colab.research.google.com/drive/1IY-nZ3RTpc_g-caI2Dtyc2GAFdFcppUl?usp=sharing){target="_blank"}

### Tuesday, September 24
-   Topic: Introduction to Neural Networks
-   Readings:
    -   ISLP Ch. 10
    -   [SLP Ch. 7](https://stanford.edu/~jurafsky/slp3/7.pdf){target="_blank"}
    -   [DL Ch. 6](https://www.deeplearningbook.org/contents/mlp.html){target="_blank"}
-   Class events: None
-   Deadlines: None
-   Class Slides: [Lecture 9](lectures/lecture9_20240924/lecture9_week5_F24.html){target="_blank"} 
-   Lab: [Lecture 9 Lab](https://colab.research.google.com/drive/1G6K70S-DUKLMXlkdZshiJILnvUIpqv85?usp=sharing){target="_blank"}

### Friday, September 27
-   Topic: Neural Networks and NLP
-   Readings:
    -   Video: ["But what is a neural network?"](https://www.youtube.com/watch?v=aircAruvnKk&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi){target="_blank"}
    -   Video: ["Gradient descent, how neural networks learn"](https://www.youtube.com/watch?v=IHZwWFHWa-w&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=2){target="_blank"}
-   Class events: None
-   Deadlines: None
-   Class Slides: [Lecture 10](lectures/lecture10_20240927/lecture10_week5_F24.html){target="_blank"}

### Tuesday, October 1
-   Topic: Word Embeddings, Part I
-   Readings:
    -   [The Illustrated Word2vec](https://jalammar.github.io/illustrated-word2vec/)
    -   [Word2vec Tutorial - The Skip-Gram Model](https://mccormickml.com/2016/04/19/word2vec-tutorial-the-skip-gram-model/)
    -   [Word2vec Tutorial Part 2 - Negative Sampling](https://mccormickml.com/2017/01/11/word2vec-tutorial-part-2-negative-sampling/)
-   Class events: None
-   Deadlines: Assignment 2 due
-   Class Slides: [Lecture 11](lectures/lecture11_20241001/lecture11_week6_F24.html){target="_blank"}

### Friday, October 4
-   Topic: Midterm Review
-   Readings: None
-   Class events: Midterm Review
-   Deadlines: None

### Tuesday, October 8

In-class Midterm

### Friday, October 11

No class - Fall Break

### Tuesday, October 15
-   Topic: Word Embeddings, Part II
-   Readings:
-   Class events: Assignment 3 goes out
-   Deadlines: None
-   Class Slides: [Lecture 12](lectures/lecture12_20241015/lecture12_week8_F24.html){target="_blank"}
-   Lab: [Lecture 12](https://colab.research.google.com/drive/1A3ViftZL73qiYBNafnfzdeXWpyBkoG6k?usp=sharing){target="_blank"}

### Friday, October 18
-   Topic: Recurrent Neural Networks
-   Readings:
    -   [SLP Ch. 8](https://stanford.edu/~jurafsky/slp3/8.pdf){target="_blank"}
-   Class events: Final project instructions go out
-   Deadlines: None
-   Class Slides: [Lecture 13](lectures/lecture13_20241018/lecture13_week8_F24.pdf){target="_blank"}